### PR TITLE
Update for Sketch 52 and overhaul for easier future updates.

### PR DESCRIPTION
**Pull request by andrewstart**
* Add type information for the JS API introduced in Sketch 49 (up to date for Sketch 52 beta).
* Update `sketch.d.ts` and `rest.d.ts` for the Sketch 52 beta.
* Changed the plugin to be symlinked via `npm run build` and output to the `sketch.d.ts` file within the repo.
* Moved the inheritance diagram generator into a scripts folder, and changed it to update the readme automatically.
* Added an npm script that runs the plugin generation command.

### CODE REVIEW

**Comment by pravdomil** [comment]
wow

**Comment by pravdomil** [comment]
I don't know if I should maintain this repo anymore, would you like to maintain it?

**Comment by andrewstart** [comment]
No, I am using it for a work project, and then will likely not touch Sketch again. It's fine to just leave the repos as they are, perhaps they'll be useful to someone in the future.

**Comment by pravdomil** [comment]
Keep the PR open so that people will notice it, Im going to archive the repository then

**Pull request closed without merging**
